// ====== KHO TỪ VỰNG B1 / B2 ======
// Mỗi dòng: [từ, nghĩa tiếng Việt, loại từ (v=động từ, n=danh từ, a=tính từ, d=trạng từ, c=liên từ), câu ví dụ có {} là chỗ trống]
// Thêm từ mới chỉ cần thêm 1 dòng vào B1 hoặc B2.
(() => {
const P = { v:'verb', n:'noun', a:'adj', d:'adv', c:'conj' };
const mk = rows => rows.map(r => ({ en:r[0], vi:r[1], pos:P[r[2]], ex:r[3] }));
window.VOCAB = {
B1: mk([
// --- động từ ---
['achieve','đạt được','v','She worked hard to {} her goal of passing the exam.'],
['afford','đủ khả năng chi trả','v',"We can't {} a new car this year."],
['argue','tranh cãi','v','My brother and I often {} about what to watch on TV.'],
['borrow','mượn','v','Can I {} your pen for a minute?'],
['depend','phụ thuộc','v','It will {} on the weather.'],
['improve','cải thiện','v','I want to {} my English by reading every day.'],
['injure','làm bị thương','v','Be careful, or you will {} yourself.'],
['invite','mời','v','We decided to {} all our neighbours to the party.'],
['manage','xoay xở được','v','Did you {} to finish the report on time?'],
['realise','nhận ra','v',"I didn't {} it was so late."],
['recommend','giới thiệu, khuyên','v','Can you {} a good restaurant near here?'],
['reduce','giảm','v','We should {} the amount of plastic we use.'],
['refuse','từ chối','v','He decided to {} the job offer.'],
['rent','thuê','v','They {} a small flat near the university.'],
['suggest','gợi ý, đề nghị','v','I {} that we leave early.'],
['accept','chấp nhận','v','Please {} my apology for being late.'],
['admit','thừa nhận','v','He had to {} that he was wrong.'],
['agree','đồng ý','v','I {} with you completely.'],
['allow','cho phép','v','Our teacher will not {} us to use phones in class.'],
['announce','thông báo','v','The airline will {} the new flight time soon.'],
['appear','xuất hiện','v','A rainbow began to {} after the rain.'],
['apply','nộp đơn, ứng tuyển','v','I want to {} for a job at the bank.'],
['arrange','sắp xếp','v','I will {} for a taxi to pick you up.'],
['attach','đính kèm','v','Please {} your photo to the email.'],
['attend','tham dự','v','Over a hundred people will {} the wedding.'],
['avoid','tránh','v','Try to {} eating too much sugar.'],
['beat','đánh bại','v','Our team hopes to {} the champions tonight.'],
['belong','thuộc về','v',"This bag doesn't {} to me."],
['cancel','hủy bỏ','v','They had to {} the picnic because of the rain.'],
['celebrate','ăn mừng, kỷ niệm','v','We always {} New Year with fireworks.'],
['choose','chọn','v','It was hard to {} between the two dresses.'],
['collect','sưu tầm, thu thập','v','My hobby is to {} old stamps.'],
['compare','so sánh','v',"Don't {} yourself with other people."],
['complain','phàn nàn','v','Customers often {} about the slow service.'],
['concentrate','tập trung','v','It is hard to {} when the room is noisy.'],
['confirm','xác nhận','v','Please {} your booking by email.'],
['connect','kết nối','v','You can {} your phone to the speaker.'],
['consider','cân nhắc','v','I will {} your offer carefully.'],
['continue','tiếp tục','v','Please {} reading from page ten.'],
['copy','sao chép, chép bài','v','He tried to {} my answers during the test.'],
['count','đếm','v','Can you {} how many chairs we have?'],
['create','tạo ra','v','Artists {} beautiful things from simple materials.'],
['cure','chữa khỏi','v','Scientists are trying to {} this disease.'],
['decorate','trang trí','v','We will {} the room with balloons.'],
['deliver','giao hàng','v','The shop will {} the sofa on Friday.'],
['describe','mô tả','v','Can you {} the man you saw?'],
['destroy','phá hủy','v','The fire could {} the whole forest.'],
['develop','phát triển','v','The company plans to {} a new app.'],
['disappear','biến mất','v','My keys seem to {} every morning.'],
['discover','khám phá ra','v','Marie Curie helped to {} radium.'],
['discuss','thảo luận','v',"Let's {} the problem over lunch."],
['divide','chia','v','Please {} the cake into eight pieces.'],
['earn','kiếm được','v','She wants to {} enough money to travel.'],
['encourage','khuyến khích','v','My parents always {} me to try new things.'],
['escape','trốn thoát','v','The prisoner managed to {} through a window.'],
['examine','khám, kiểm tra','v','The doctor will {} your knee.'],
['expect','mong đợi, dự kiến','v','I {} it will rain this afternoon.'],
['explain','giải thích','v','Can you {} how this machine works?'],
['explore','thám hiểm','v','We want to {} the old city on foot.'],
['fail','thất bại, trượt','v',"If you don't study, you will {} the exam."],
['fix','sửa chữa','v','Can you {} my bike?'],
['forgive','tha thứ','v','Please {} me for being late.'],
['gather','tập hợp','v','Everyone will {} in the hall at noon.'],
['guess','đoán','v','Can you {} how old she is?'],
['hire','thuê (người)','v','The restaurant plans to {} two new waiters.'],
['hurry','vội vã','v',"We must {} or we'll miss the train."],
['ignore','phớt lờ','v',"Don't {} the warning signs."],
['include','bao gồm','v','The price will {} breakfast.'],
['introduce','giới thiệu (người)','v','Let me {} you to my sister.'],
['join','tham gia','v','Would you like to {} our team?'],
['judge','đánh giá, phán xét','v',"Don't {} people by their clothes."],
['lend','cho mượn','v','Could you {} me ten dollars until Friday?'],
['lift','nâng lên','v','He was too weak to {} the box.'],
['mention','đề cập','v','He forgot to {} that the shop closes early on Mondays.'],
['notice','nhận thấy','v','Did you {} her new haircut?'],
['obey','vâng lời, tuân theo','v','Children must {} the rules.'],
['offer','đề nghị, biếu','v','He will {} to drive us home.'],
['organise','tổ chức','v','Who will {} the school trip?'],
['pack','đóng gói','v','I need to {} my suitcase tonight.'],
['prefer','thích hơn','v','I {} tea to coffee.'],
['prepare','chuẩn bị','v','Please {} your presentation in advance.'],
['prevent','ngăn ngừa','v','Washing hands can {} many illnesses.'],
['promise','hứa','v','I {} I will call you tomorrow.'],
['protect','bảo vệ','v','Sunscreen helps {} your skin.'],
['prove','chứng minh','v','Can you {} that you are over eighteen?'],
['provide','cung cấp','v','The hotel will {} free breakfast.'],
['punish','trừng phạt','v','It is wrong to {} a child for telling the truth.'],
['regret','hối tiếc','v','I {} not studying harder at school.'],
['relax','thư giãn','v','I like to {} by listening to music.'],
['remind','nhắc nhở','v','Please {} me to buy milk.'],
['replace','thay thế','v','We need to {} the old windows.'],
['report','báo cáo, trình báo','v','You should {} the theft to the police.'],
['rescue','cứu hộ','v','Firefighters came to {} the cat.'],
['retire','nghỉ hưu','v','My grandfather will {} next year.'],
['search','tìm kiếm','v','I had to {} the whole house for my keys.'],
['share','chia sẻ','v','Would you like to {} my umbrella?'],
['shout','la hét','v',"Please don't {} at the children."],
['solve','giải quyết','v','We need to {} this problem quickly.'],
['spill','làm đổ, làm tràn','v','Careful, or you will {} your drink.'],
['spread','lan rộng','v','The news began to {} quickly.'],
['stare','nhìn chằm chằm','v','It is rude to {} at people.'],
['succeed','thành công','v','If you try hard, you will {}.'],
['suffer','chịu đau khổ','v','Many people {} from headaches.'],
['support','ủng hộ','v','My family will always {} my decision.'],
['surprise','làm ngạc nhiên','v','I want to {} her with a gift.'],
['survive','sống sót','v','Few animals can {} in the desert.'],
['translate','dịch','v','Can you {} this letter into English?'],
['trust','tin tưởng','v',"You can {} me. I won't tell anyone."],
['warn','cảnh báo','v','I must {} you about the dog.'],
['waste','lãng phí','v',"Don't {} water while brushing your teeth."],
// --- danh từ ---
['candidate','ứng viên','n','Every {} for the job must send a CV.'],
['damage','thiệt hại','n','The storm caused serious {} to the village.'],
['delay','sự chậm trễ','n','There was a long {} because of the snow.'],
['journey','chuyến đi dài','n','The {} from Hanoi to Hue takes about twelve hours by train.'],
['neighbour','hàng xóm','n','Our {} plays loud music every night.'],
['receipt','biên lai, hóa đơn','n','Keep the {} in case you want to return it.'],
['accident','tai nạn','n','The driver was lucky to survive the {}.'],
['adventure','cuộc phiêu lưu','n','The children went on a great {} in the forest.'],
['advantage','lợi thế','n','Speaking two languages is a big {}.'],
['advertisement','quảng cáo','n','I saw your {} in the newspaper.'],
['audience','khán giả','n','The {} clapped loudly after the show.'],
['bargain','món hời','n','These shoes were only five dollars. That was a real {}!'],
['border','biên giới','n','We crossed the {} into Cambodia by bus.'],
['career','sự nghiệp','n','She wants to build a successful {} in medicine.'],
['century','thế kỷ','n','This church was built more than one {} ago.'],
['climate','khí hậu','n','The {} here is hot and wet.'],
['competition','cuộc thi','n','She won first prize in the singing {}.'],
['crime','tội phạm','n','There is very little {} in this town.'],
['custom','phong tục','n','Giving red envelopes is a traditional {}.'],
['danger','mối nguy hiểm','n','The sign warns of {} ahead.'],
['decision','quyết định','n','It was a difficult {} to make.'],
['degree','bằng đại học','n','He has a university {} in engineering.'],
['diet','chế độ ăn','n','A healthy {} includes lots of vegetables.'],
['disaster','thảm họa','n','The flood was a terrible {} for the town.'],
['discount','giảm giá','n','Students get a ten percent {}.'],
['distance','khoảng cách','n','The {} between the two cities is 200 km.'],
['education','giáo dục','n','Free {} is important for every child.'],
['emergency','tình huống khẩn cấp','n','Call this number in case of {}.'],
['environment','môi trường','n','We must protect the {}.'],
['equipment','thiết bị','n','The gym has modern {}.'],
['experience','kinh nghiệm','n','She has ten years of {} in teaching.'],
['fashion','thời trang','n','Short skirts are back in {}.'],
['festival','lễ hội','n','Thousands of people come to the music {}.'],
['fault','lỗi (của ai)','n',"It's not your {}. Nobody blames you."],
['flavour','hương vị','n','My favourite ice cream {} is chocolate.'],
['forecast','dự báo','n','The weather {} says it will snow.'],
['guide','hướng dẫn viên','n','The tour {} showed us the castle.'],
['habit','thói quen','n','Biting your nails is a bad {}.'],
['height','chiều cao','n','What is the {} of that tower?'],
['hobby','sở thích','n','Photography is my favourite {}.'],
['injury','vết thương, chấn thương','n','He missed the match because of a knee {}.'],
['insurance','bảo hiểm','n','Do you have travel {}?'],
['invention','phát minh','n','The telephone was a great {}.'],
['journalist','nhà báo','n','The {} asked the mayor a difficult question.'],
['knowledge','kiến thức','n','He has a lot of {} about computers.'],
['luggage','hành lý','n','Please keep your {} with you at all times.'],
['manager','quản lý','n',"I'd like to speak to the {}, please."],
['memory','trí nhớ, ký ức','n','I have a good {} for faces.'],
['mistake','lỗi sai','n','I made a silly {} in the test.'],
['opinion','ý kiến','n','In my {}, the film was too long.'],
['passenger','hành khách','n','Every {} must wear a seat belt.'],
['patient','bệnh nhân','n','The nurse takes care of each {}.'],
['pollution','ô nhiễm','n','Air {} is a serious problem in big cities.'],
['prize','giải thưởng','n','The winner will receive a cash {}.'],
['quality','chất lượng','n','The {} of the food was excellent.'],
['reason','lý do','n','What is the {} for your lateness?'],
['refund','tiền hoàn lại','n','The shop gave me a full {}.'],
['result','kết quả','n',"I'm waiting for my exam {}."],
['risk','rủi ro','n','Smoking increases the {} of cancer.'],
['salary','tiền lương','n','He earns a good {}.'],
['schedule','lịch trình','n','I have a very busy {} this week.'],
['silence','sự im lặng','n','The room fell into complete {}.'],
['survey','cuộc khảo sát','n','The {} shows that most students like pizza.'],
['temperature','nhiệt độ','n','The {} dropped below zero last night.'],
['tourist','khách du lịch','n','Every {} wants to see the old temple.'],
['tradition','truyền thống','n','It is a family {} to eat together on Sundays.'],
['traffic','giao thông','n','The {} was terrible this morning.'],
['view','quang cảnh','n','The room has a lovely {} of the sea.'],
['wedding','đám cưới','n','We were invited to their {} in June.'],
// --- tính từ ---
['comfortable','thoải mái','a','This sofa is really {}.'],
['crowded','đông đúc','a','The bus was so {} that I had to stand.'],
['embarrassed','xấu hổ, ngượng','a','I felt so {} when I forgot her name.'],
['enormous','khổng lồ','a','The elephant was {}.'],
['exhausted','kiệt sức','a','After the long run, he was completely {}.'],
['familiar','quen thuộc','a','Her face looks {}. Have we met before?'],
['generous','hào phóng','a','He is very {} and always shares his money.'],
['nervous','lo lắng, hồi hộp','a','She was {} before the job interview.'],
['valuable','có giá trị','a','This old painting is very {}.'],
['amazing','tuyệt vời, kinh ngạc','a','The view from the top was {}.'],
['ancient','cổ xưa','a','The temple is over two thousand years old. It is really {}.'],
['awful','tồi tệ','a','The weather was {} all week.'],
['bored','chán','a','She was {} during the long lecture.'],
['brave','dũng cảm','a','The {} firefighter saved the child.'],
['careful','cẩn thận','a','Be {} on the wet floor.'],
['convenient','thuận tiện','a','The hotel is {} for the station.'],
['curious','tò mò','a','Children are naturally {} about the world.'],
['dangerous','nguy hiểm','a','It is {} to swim here.'],
['disappointed','thất vọng','a','I was {} with my exam result.'],
['eager','háo hức','a','She was {} to start her new job.'],
['empty','trống rỗng','a','The fridge is completely {}.'],
['fair','công bằng','a',"It's not {} that he gets more than us."],
['fit','khỏe mạnh, cân đối','a','He runs every day to stay {}.'],
['foolish','ngớ ngẩn','a','It was {} to leave the door open.'],
['frightened','sợ hãi','a','The little girl was {} of the dark.'],
['furious','giận dữ','a','Dad was {} when he saw the broken window.'],
['guilty','có tội, cảm thấy có lỗi','a','I felt {} about lying to her.'],
['honest','trung thực','a','Please be {} with me.'],
['impatient','thiếu kiên nhẫn','a',"Don't be so {}. The food will be ready soon."],
['impressive','ấn tượng','a','Her speech was truly {}.'],
['independent','độc lập','a','She has been {} since she was eighteen.'],
['jealous','ghen tị','a',"He felt {} of his brother's success."],
['lazy','lười biếng','a','He was too {} to wash the dishes.'],
['lonely','cô đơn','a','She felt {} in the big city.'],
['loyal','trung thành','a','Dogs are very {} animals.'],
['narrow','hẹp','a','The street was too {} for the truck.'],
['necessary','cần thiết','a','It is {} to book a table in advance.'],
['noisy','ồn ào','a','The neighbours were very {} last night.'],
['obvious','hiển nhiên','a','It was {} that he was lying.'],
['peaceful','yên bình','a','The village is quiet and {}.'],
['polite','lịch sự','a','It is {} to say thank you.'],
['proud','tự hào','a','I am so {} of you.'],
['rare','hiếm','a','This bird is very {}.'],
['ridiculous','lố bịch, vô lý','a','That price is {}!'],
['rough','gồ ghề, dữ dội','a','The sea was very {} yesterday.'],
['selfish','ích kỷ','a',"Don't be {}. Share your toys."],
['sensible','biết điều, hợp lý','a','It is {} to wear a coat in winter.'],
['shy','nhút nhát','a','He is too {} to talk to strangers.'],
['tidy','gọn gàng','a','Please keep your room {}.'],
['tiny','nhỏ xíu','a','The house is {}. It has only one room.'],
['unusual','khác thường','a','It is {} to see snow here in April.'],
['annoyed','bực mình','a','I was {} when he kept interrupting me.'],
['strict','nghiêm khắc','a','Our teacher is very {} about homework.'],
['ordinary','bình thường','a','It was just a very {} day, nothing special.'],
// --- trạng từ ---
['suddenly','đột nhiên','d','The lights went out {}.'],
['recently','gần đây','d','I have {} started learning guitar.'],
['probably','có lẽ, nhiều khả năng','d','It is {} going to rain tomorrow, but I am not certain.'],
['immediately','ngay lập tức','d','Call an ambulance {}!'],
['fortunately','may mắn thay','d','{}, nobody was hurt in the accident.'],
['definitely','chắc chắn','d','I will {} come to your party.'],
['especially','đặc biệt là','d','I love fruit, {} mangoes.'],
['properly','đúng cách','d',"The door doesn't close {}."],
['nearly','suýt, gần như','d','I {} fell asleep in class.'],
['carefully','một cách cẩn thận','d','Read the instructions {}.'],
['rarely','hiếm khi','d','We {} eat out. We prefer cooking at home.'],
['instead','thay vào đó','d',"I didn't have tea, so I had coffee {}."]
]),
B2: mk([
// --- động từ ---
['acknowledge','thừa nhận','v','He refused to {} that he had made a mistake.'],
['anticipate','dự đoán, lường trước','v','We {} that sales will rise next quarter.'],
['assume','cho rằng, giả định','v',"Don't just {} he knows. Ask him."],
['deteriorate','xấu đi','v','If you do nothing, the situation will {} rapidly.'],
['diminish','giảm bớt','v','Her enthusiasm began to {} after the third failure.'],
['elaborate','giải thích chi tiết','v','Could you {} on your idea a little more?'],
['enhance','nâng cao, tăng cường','v','Good lighting can {} the atmosphere of a room.'],
['negotiate','đàm phán','v','The unions will {} with the company about pay.'],
['persuade','thuyết phục','v','I tried to {} him to change his mind.'],
['predict','dự báo','v','No one can {} exactly what will happen.'],
['sustain','duy trì','v','It is hard to {} such a fast pace for a whole year.'],
['tolerate','chịu đựng, khoan dung','v',"I can't {} people who are rude to waiters."],
['withdraw','rút lại, rút lui','v','She decided to {} her application.'],
['abandon','từ bỏ, bỏ rơi','v','They had to {} the car in the snow.'],
['absorb','hấp thụ','v','Plants {} water through their roots.'],
['accumulate','tích lũy','v','Dust will {} if you never clean.'],
['adapt','thích nghi','v','It took me months to {} to the cold weather.'],
['adjust','điều chỉnh','v','You can {} the height of the chair.'],
['advocate','ủng hộ, ra sức bênh vực','v','Many doctors {} regular exercise for older adults.'],
['allocate','phân bổ','v','The council will {} more money to schools.'],
['alter','thay đổi','v','We had to {} our plans at the last minute.'],
['amend','sửa đổi (luật, văn bản)','v','Parliament voted to {} the law.'],
['analyse','phân tích','v','Scientists will {} the results carefully.'],
['appreciate','trân trọng, cảm kích','v','I really {} your help.'],
['approach','tiếp cận','v',"Let's {} the problem from a different angle."],
['assess','đánh giá','v',"Teachers {} students' progress every term."],
['assign','giao (việc)','v','The manager will {} a new task to each employee.'],
['attain','đạt được (sau nỗ lực)','v','It takes years to {} fluency in a language.'],
['cease','ngừng','v','The factory will {} production next month.'],
['circulate','lưu thông, lưu hành','v','Blood must {} around the body.'],
['clarify','làm rõ','v','Could you {} what you mean?'],
['coincide','trùng khớp','v','My holiday will {} with her birthday.'],
['collaborate','hợp tác','v','The two universities will {} on the project.'],
['collapse','sụp đổ','v','The old bridge could {} at any moment.'],
['commence','bắt đầu (trang trọng)','v','The ceremony will {} at noon.'],
['compensate','bồi thường','v','The airline will {} passengers for the delay.'],
['compile','biên soạn, tổng hợp','v','She helped to {} a dictionary of slang.'],
['comply','tuân thủ','v','All drivers must {} with the law.'],
['conceal','che giấu','v','He tried to {} his disappointment.'],
['conduct','tiến hành','v','Scientists will {} an experiment next week.'],
['confront','đối mặt','v','You must {} your fears.'],
['contradict','mâu thuẫn với','v','Your story seems to {} what he told us.'],
['contribute','đóng góp','v','Everyone can {} to the cleanup.'],
['convey','truyền đạt','v','Music can {} emotions without words.'],
['criticise','chỉ trích','v',"It's easy to {}, but harder to help."],
['cultivate','trồng trọt, trau dồi','v','Farmers here {} rice and tea.'],
['decline','từ chối lịch sự','v','She had to {} the invitation.'],
['deduce','suy luận','v','From the clues, we can {} who stole it.'],
['demonstrate','trình diễn, chứng minh','v','Let me {} how the machine works.'],
['depict','miêu tả, khắc họa','v','The painting seems to {} a quiet village at dawn.'],
['derive','bắt nguồn','v','Many English words {} from Latin.'],
['detect','phát hiện','v','The alarm will {} smoke.'],
['deviate','lệch khỏi','v','Please do not {} from the plan.'],
['dispose','vứt bỏ, xử lý','v','How do you {} of old batteries?'],
['distinguish','phân biệt','v',"It's hard to {} between the twins."],
['distribute','phân phát','v','Volunteers will {} food to families.'],
['dominate','thống trị, chi phối','v','One company seems to {} the market.'],
['eliminate','loại bỏ','v','We must {} all errors before printing.'],
['emerge','nổi lên, xuất hiện','v','A new leader will {} from the crisis.'],
['emphasise','nhấn mạnh','v','The teacher used a bright pen to {} key points.'],
['enable','giúp có thể','v','This app will {} you to learn faster.'],
['encounter','gặp phải','v','Travellers often {} problems with language.'],
['enforce','thi hành (luật)','v','The police must {} the law.'],
['establish','thành lập','v','They plan to {} a charity next year.'],
['estimate','ước tính','v',"I'd {} the trip will take three hours."],
['evolve','tiến hóa, phát triển dần','v','Languages {} over time.'],
['exceed','vượt quá','v','Do not {} the speed limit.'],
['exclude','loại trừ','v','Please do not {} anyone from the game.'],
['exploit','khai thác, bóc lột','v','Some companies {} cheap labour.'],
['expose','vạch trần','v','The journalist hopes to {} corruption.'],
['facilitate','tạo điều kiện thuận lợi','v','Technology can {} communication between countries.'],
['fluctuate','dao động','v','Prices {} throughout the year.'],
['foster','nuôi dưỡng, thúc đẩy','v','Good teachers {} a love of learning.'],
['generate','tạo ra, phát (điện)','v','Wind turbines {} electricity.'],
['highlight','làm nổi bật','v','The report will {} the main problems.'],
['hinder','cản trở','v','Bad weather may {} the rescue.'],
['illustrate','minh họa','v','Let me {} my point with an example.'],
['imply','ngụ ý','v',"Are you trying to {} that I'm lying?"],
['impose','áp đặt','v','The government will {} a new tax.'],
['incorporate','kết hợp, đưa vào','v',"We'll {} your ideas into the design."],
['indicate','chỉ ra, cho thấy','v','Studies {} that sleep improves memory.'],
['initiate','khởi xướng','v','The mayor will {} a recycling scheme.'],
['integrate','hòa nhập','v','New students often find it hard to {} at first.'],
['interpret','diễn giải','v','Different people {} the poem differently.'],
['interfere','can thiệp','v',"Please don't {} in my private life."],
['investigate','điều tra','v','Police will {} the robbery.'],
['isolate','cách ly, cô lập','v','Doctors had to {} the patient to stop the infection.'],
['justify','biện minh','v','Nothing can {} such cruelty.'],
['maintain','bảo dưỡng, duy trì','v','Regular servicing will {} your car in good condition.'],
['manipulate','thao túng','v','Advertisers often {} our emotions.'],
['neglect','bỏ bê','v',"Don't {} your health."],
['oblige','bắt buộc','v','The law will {} companies to recycle.'],
['obtain','có được, đạt được','v','It is not easy to {} a visa.'],
['overcome','vượt qua','v','She worked hard to {} her fear of flying.'],
['perceive','nhận thức, nhìn nhận','v','How do people {} the new policy?'],
['pursue','theo đuổi','v','She moved abroad to {} her dream.'],
['reinforce','củng cố','v','Practice will {} what you learned in class.'],
['reject','bác bỏ','v','The committee decided to {} the proposal.'],
['resolve','giải quyết (tranh chấp)','v','We hope to {} the dispute peacefully.'],
['restrict','hạn chế','v','Parents should {} the time children spend online.'],
['retain','giữ lại, ghi nhớ','v',"It's hard to {} so much information."],
['reveal','tiết lộ','v','He refused to {} his secret.'],
['simulate','mô phỏng','v','The program can {} flight conditions.'],
['stimulate','kích thích','v',"Games can {} a child's imagination."],
['subscribe','đăng ký (dài hạn)','v',"I'd like to {} to the magazine."],
['substitute','thay thế bằng','v','You can {} honey for sugar.'],
['undermine','làm suy yếu','v','Constant criticism will {} her confidence.'],
['undergo','trải qua','v','He had to {} a long operation.'],
['utilise','tận dụng','v','We should {} every resource.'],
['verify','xác minh','v','Please {} your identity at the desk.'],
['violate','vi phạm','v','Anyone who tries to {} the rules will be fined.'],
// --- danh từ ---
['benefit','lợi ích','n','One major {} of working from home is saving time.'],
['conflict','xung đột','n','There was a serious {} between the two departments.'],
['consequence','hậu quả','n','You must accept the {} of your decisions.'],
['insight','sự thấu hiểu sâu sắc','n','The book gives readers valuable {} into Japanese culture.'],
['obstacle','trở ngại','n','Lack of money was the biggest {} to her plan.'],
['witness','nhân chứng','n','The police are asking every {} to the accident to come forward.'],
['access','quyền truy cập, lối vào','n','Students have free {} to the library.'],
['agenda','chương trình nghị sự','n','The first item on the {} was the budget.'],
['alternative','giải pháp thay thế','n','There is no {} to this plan.'],
['ambition','tham vọng','n','Her {} is to become prime minister.'],
['analysis','sự phân tích','n','A detailed {} of the data took a week.'],
['aspect','khía cạnh','n','Money is only one {} of the problem.'],
['assumption','giả định','n','Your argument is based on a false {}.'],
['atmosphere','bầu không khí','n','The café has a warm and friendly {}.'],
['authority','chính quyền, thẩm quyền','n','Only the local {} can give permission.'],
['barrier','rào cản','n','Language can be a big {} for newcomers.'],
['bias','sự thiên vị','n','The referee showed clear {} towards the home team.'],
['capacity','sức chứa, năng lực','n',"The stadium's total {} is 40,000 people."],
['category','nhóm, loại','n','Each item belongs to one main {}.'],
['commitment','sự cam kết','n','Marriage requires great {}.'],
['consensus','sự đồng thuận','n','They finally reached {} on the budget.'],
['constraint','sự ràng buộc, hạn chế','n','Time is the biggest {} on this project.'],
['context','ngữ cảnh','n','You can guess the meaning from the {}.'],
['crisis','cuộc khủng hoảng','n','The country is facing an economic {}.'],
['debate','cuộc tranh luận','n','There was a heated {} about the new law.'],
['dilemma','thế tiến thoái lưỡng nan','n',"I'm facing a real {}: stay or leave."],
['discrimination','sự phân biệt đối xử','n','Laws protect workers from {}.'],
['dispute','tranh chấp','n','The two countries are in a long {} over land.'],
['diversity','sự đa dạng','n','The school celebrates cultural {}.'],
['efficiency','hiệu suất','n','The new system has improved {}.'],
['emphasis','sự nhấn mạnh','n','The school puts great {} on reading.'],
['evidence','bằng chứng','n','There is no {} that he was there.'],
['expertise','chuyên môn','n','We need someone with technical {}.'],
['factor','yếu tố','n','Price is an important {} when buying a car.'],
['framework','khuôn khổ','n','The new law sets the legal {} for online shopping.'],
['hypothesis','giả thuyết','n','Scientists tested their {} in the lab.'],
['impact','tác động','n','Social media has a huge {} on teenagers.'],
['incentive','sự khuyến khích, động lực','n','Higher pay gives workers extra {} to work hard.'],
['infrastructure','cơ sở hạ tầng','n','The country needs better roads and other {}.'],
['initiative','sáng kiến, tính chủ động','n','She took the {} and organised the party.'],
['innovation','sự đổi mới','n','Technology drives {} in business.'],
['legislation','pháp luật, đạo luật','n','New {} will ban plastic bags.'],
['margin','biên độ, chênh lệch','n','She won by a narrow {}.'],
['mechanism','cơ chế','n','The body has a natural cooling {}.'],
['objective','mục tiêu','n','Our main {} is to cut costs.'],
['outcome','kết quả','n','Nobody could predict the final {}.'],
['perspective','góc nhìn','n','Try to see the situation from her {}.'],
['phenomenon','hiện tượng','n','The northern lights are a natural {}.'],
['policy','chính sách','n','The company has a strict no-smoking {}.'],
['potential','tiềm năng','n','She has great {} as a singer.'],
['principle','nguyên tắc','n','I never lie. It is a matter of {}.'],
['priority','sự ưu tiên','n','Safety is our top {}.'],
['procedure','quy trình','n','The usual {} for booking is online.'],
['proportion','tỉ lệ','n','A large {} of students walk to school.'],
['reputation','danh tiếng','n','The hotel has an excellent {}.'],
['resource','nguồn tài nguyên','n','Water is a precious natural {}.'],
['response','phản hồi','n','We are waiting for their {} to our letter.'],
['scheme','kế hoạch, chương trình','n','The city has launched a new recycling {}.'],
['sector','khu vực, ngành','n','She works in the public {}.'],
['sequence','trình tự','n','Put the pictures in the correct {}.'],
['stability','sự ổn định','n','The country enjoys political {}.'],
['strategy','chiến lược','n','We need a clear {} to win.'],
['trend','xu hướng','n','There is a growing {} towards working from home.'],
['welfare','phúc lợi','n','The charity looks after the {} of children.'],
// --- tính từ ---
['adequate','đủ, thỏa đáng','a','The food supply was not {} for such a large group.'],
['ambiguous','mơ hồ, nhập nhằng','a','The instructions were {}, so everyone understood them differently.'],
['controversial','gây tranh cãi','a','The new law is highly {}, and many people protest against it.'],
['inevitable','không thể tránh khỏi','a','With so much traffic, a delay was {}.'],
['mandatory','bắt buộc','a','Wearing a helmet is {} for all cyclists here.'],
['reliable','đáng tin cậy','a','My car is very {}. It never breaks down.'],
['reluctant','miễn cưỡng, ngần ngại','a','She was {} to speak in front of the whole class.'],
['scarce','khan hiếm','a','Fresh water is {} in the desert.'],
['substantial','đáng kể, lớn','a','The company made very {} profits last year.'],
['vulnerable','dễ bị tổn thương','a','Young children are especially {} to infections.'],
['abstract','trừu tượng','a','Freedom is a very {} concept.'],
['accurate','chính xác','a','The map is not {}.'],
['apparent','rõ ràng','a','It soon became {} that he was lying.'],
['arbitrary','tùy tiện','a','The rules seem {} and unfair.'],
['authentic','chính gốc, chân thực','a','The restaurant serves {} Italian food.'],
['beneficial','có lợi','a','Regular exercise is {} to your health.'],
['bizarre','kỳ quái','a','That story is so {}! I do not believe it.'],
['blunt','thẳng thừng','a','He was {} and told her the truth.'],
['coherent','mạch lạc','a','Her essay was clear and {}.'],
['compatible','tương thích','a','This charger is not {} with my phone.'],
['comprehensive','toàn diện','a','The guide includes very {} information on hotels.'],
['conventional','thông thường, truyền thống','a','She prefers {} methods to new ones.'],
['crucial','then chốt','a','Good sleep is {} for learning.'],
['dedicated','tận tâm','a','She is very {} to her work.'],
['deliberate','cố ý','a','It was not an accident. It was {}.'],
['dense','dày đặc','a',"The fog was so {} that we couldn't see."],
['distinct','khác biệt rõ rệt','a','The two styles are quite {} from each other.'],
['diverse','đa dạng','a','The population here is very {}.'],
['dramatic','đột ngột, ấn tượng','a','The rise in prices was very {}.'],
['eligible','đủ điều kiện','a','Only adults are {} to vote.'],
['essential','thiết yếu','a','Water is {} for life.'],
['explicit','rõ ràng, minh bạch','a','He gave {} instructions, so everyone understood.'],
['fundamental','cơ bản','a','Honesty is {} to any friendship.'],
['genuine','chân thật','a','She seemed {} when she said sorry.'],
['inherent','vốn có','a','Every sport has some {} risk.'],
['intense','dữ dội, mãnh liệt','a','The heat was {} at noon.'],
['legitimate','hợp pháp','a','Check that the business is {} and registered.'],
['literal','theo nghĩa đen','a','The {} meaning of the word is water.'],
['minimal','tối thiểu','a','The damage was {}. Only a small scratch.'],
['moderate','vừa phải','a','Do {} exercise, such as walking.'],
['notorious','khét tiếng','a','The road is {} for accidents.'],
['obsolete','lỗi thời','a','Typewriters are now {}.'],
['overwhelming','choáng ngợp, áp đảo','a','The support was {}. Thousands wrote letters.'],
['partial','một phần','a','The refund was only {}, not full.'],
['persistent','kiên trì, dai dẳng','a','She is {}. She never gives up.'],
['plausible','có vẻ hợp lý','a','His excuse sounds {}.'],
['profound','sâu sắc','a',"The book's influence was {}."],
['prominent','nổi bật, có tiếng','a','She is {} in local politics.'],
['radical','triệt để, cấp tiến','a','The company needs {} changes.'],
['rational','có lý trí','a','Be {}. Think before you decide.'],
['relevant','liên quan','a','Please include only {} information.'],
['remarkable','đáng chú ý','a','Her recovery was truly {}.'],
['resilient','kiên cường, mau phục hồi','a','Children are often more {} than adults think.'],
['rigid','cứng nhắc','a','The rules are too {} to change.'],
['subtle','tinh tế, khó nhận ra','a','The difference between the colours is very {}.'],
['superficial','nông cạn, bề ngoài','a','Their friendship was shallow and {}.'],
['tangible','hữu hình, rõ ràng','a','We need {} proof, not promises.'],
['temporary','tạm thời','a','The job is only {}. It ends in June.'],
['trivial','nhỏ nhặt','a',"Don't argue over such {} matters."],
['unprecedented','chưa từng có','a','The size of the crowd was {}.'],
['valid','hợp lệ','a','Your ticket is no longer {}.'],
['vast','rộng lớn','a','The desert is {}. It covers millions of kilometres.'],
['visible','có thể nhìn thấy','a','The stars are not {} in the city.'],
['vivid','sống động','a','She has {} memories of her childhood.'],
['unlikely','không chắc xảy ra','a','It is {} to rain. The sky is clear.'],
// --- trạng từ / liên từ ---
['approximately','xấp xỉ','d','The trip takes {} two hours.'],
['consequently','do đó','d',"He didn't study. {}, he failed."],
['deliberately','cố tình','d','He {} broke the window.'],
['eventually','cuối cùng','d','After many attempts, she {} succeeded.'],
['furthermore','hơn nữa','d','The flat is cheap. {}, it is close to the station.'],
['increasingly','ngày càng','d','Life is becoming {} expensive.'],
['nevertheless','tuy nhiên','d','It was raining. {}, we went for a walk.'],
['predominantly','chủ yếu là','d','The audience was {} young people.'],
['presumably','có lẽ, chắc là','d',"She's not here, so {} she's still at work."],
['relatively','tương đối','d','The test was {} easy.'],
['subsequently','sau đó','d','He was arrested and {} sentenced.'],
['thoroughly','kỹ lưỡng','d','Wash your hands {}.'],
['whereas','trong khi (đối lập)','c','He is tall, {} his brother is short.']
])
};
})();
